// frontend/src/pages/HomePage.jsx

import React from "react";

const HomePage = () => {
  return (
    <div>
      <h1>Home Page</h1>
      <p>TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ TRANG CHỦ</p>
    </div>
  );
};

export default HomePage;
